Fix pages handling
Previously implemented handling of data pages coming
from pulp resulted in:
`Cancel next page due to GC: True`
whenever page.next was processed.

This now has been mitigated and should work as intended
and all pages are properly processed.
The solution is possibly not optimal as it adds blocking
while we wait for next page.

Unrelated addtion:
* bump version of black because of
`ImportError: cannot import name '_unicodefun' from 'click'`